baseurl = "https://nixhou.github.io/Nix_Life/"  # Include trailing slash
title = "Nix Life"
theme = "newsroom"
author = "Nix"
canonifyurls = true

[markup]
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = false # change to true to enable inclusion of rawHTML and math functions
    xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    tabWidth = 2

[params]
  faviconsDir = "images/icons/" # with a trailing slash
  blogDir = "post" # edit
